### ISSUE TITLE
[BUG] Level State Throwing Null Reference

### ISSUE THREAD

**Issue by tjmareng** [HuskyGameDev/2019f-team10#25]
The LevelState object within the Inventory script is throwing a NullReferenceException when LevelState.IsGamePaused is called.

![Null Reference](https://user-images.githubusercontent.com/46637887/66049133-d189c480-e4f8-11e9-802e-7be231520f2b.PNG)

**Comment by cofl** [comment]
1. It's not in LevelState.
2. Put the RequiredLevelObject prefab in your scene.

**Comment by cofl** [comment]
Keep in mind that the Inventory script at the root of the Script directory is deprecated and going to be removed.

**Comment by cofl** [comment]
The old Inventory script has been removed and replaced. So long as the prefab is present, the inventory will work.
