### ISSUE TITLE
Press 'E' to Interact

### ISSUE THREAD

**Issue by tjmareng** [HuskyGameDev/2019f-team10#33]
- [x] Expand area of interaction
- [x] Implement pop-up which tells the player they can interact with an object or NPC by pressing 'E'
- [x] Create 'E to Interact" graphic
- [x] Graphic appears next to object that the player can interact with
- [x] Implement changes to existing scenes

**Comment by cofl** [comment]
If you see the changes I made in my last 2 commits, if we're using `Interactable`, we can create a child game object with an arbitrary trigger collider, and hook up arbitrary functions to it using the events.

I genericized your dialog interaction code to work with that.

**Comment by tjmareng** [comment]
Sounds good! I will take a look at it
